name: Update data

on:
  workflow_dispatch:    # ✅ Cho phép chạy thủ công
  push:                 # ✅ Chạy khi push commit mới
    branches:
      - main
  schedule:
    - cron: 35 11 * * * # 6:35 PM in Vietnam

jobs:
  update-data:
    runs-on: ubuntu-24.04
    permissions:         # ✅ Cho phép workflow push code
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: fetch data
        run: python src/fetch.py

      - name: analyze data
        run: python src/analyze.py

      - name: get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: push changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: Updated ${{ env.date }}
          email: action@github.com
          name: GitHub Action
